name: syncfusion_flutter_officecore
description: Syncfusion Flutter Office Core is a dependant library for Syncfusion Flutter XlsIO, written natively in Dart for creating Excel from scratch.
version: 19.1.54-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_officecore

environment:
  sdk: ">=2.12.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_officecore:
    git:
      url: git@github.com:slui861/flutter-widgets.git
      path: packages/syncfusion_flutter_officecore